tau/osu.Game.Rulesets.tau/Judgements/TauJudgement.cs
I raised the maximum judgement from `Great` to `Perfect` following what smoogi said.
Fixes #12 .
=> Fix "Perfect" judgement allowing players to have more than 100 acc

tau/osu.Game.Rulesets.tau/Mods/TauModBlinds.cs, tau/osu.Game.Rulesets.tau/Mods/TauModRelax.cs, tau/osu.Game.Rulesets.tau/UI/Cursor/tauCursor.cs
Fixes #20, as it creates maintainability changes that improve the quality of the code. In-game haven't been done yet, though.
=> CodeFactor Inconsistencies

osu.Game.Rulesets.tau/Objects/Drawables/DrawabletauHitObject.cs, osu.Game.Rulesets.tau/UI/tauPlayfield.cs
=> Fix scaling issue

osu.Game.Rulesets.tau/Mods/TauModBlinds.cs
It was previously crashing on first hit object
=> Fix Blinds mod

osu.Game.Rulesets.tau/Replays/tauReplayFrame.cs, osu.Game.Rulesets.tau/UI/TauReplayRecorder.cs, osu.Game.Rulesets.tau/UI/tauDrawableRuleset.cs, osu.Game.Rulesets.tau/osu.Game.Rulesets.tau.csproj, osu.Game.Rulesets.tau/tauInputManager.cs, osu.Game.Rulesets.tau/tauRuleset.cs
updating from ppy/osu#8428
Requires 2020.325.0 or higher version of osu!lazer to work
=> Add local replay support for tau

osu.Game.Rulesets.tau/UI/Cursor/tauCursor.cs, osu.Game.Rulesets.tau/UI/tauDrawableRuleset.cs, osu.Game.Rulesets.tau/UI/tauPlayfield.cs
=> Fix CircleSize not being affected

osu.Game.Rulesets.tau/osu.Game.Rulesets.tau.csproj
=> Update osu packages

.vscode/launch.json, .vscode/tasks.json
Will be helpful for VSCode users
=> Add Visual Studio Code task/launch configurations

osu.Game.Rulesets.tau/Objects/Drawables/DrawabletauHitObject.cs, osu.Game.Rulesets.tau/UI/Cursor/tauCursor.cs
Fixes #55 
A dirty fix imo, but I didn't really want to rework whatever exists already.
=> Fix beatsize option affecting gameplay

osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs, osu.Game.Rulesets.Tau/Mods/TauModRelax.cs, osu.Game.Rulesets.Tau/Objects/Beat.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauHitObject.cs, osu.Game.Rulesets.Tau/Objects/TauHitObject.cs, osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs, osu.Game.Rulesets.Tau/UI/TauDrawableRuleset.cs, osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
Resolves #7 
This will save a lot of trouble later down the line, while also clearly separating different note types.
=> Make TauHitObject abstract

osu.Game.Rulesets.Tau/UI/Components/PlayfieldVisualization.cs, osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
This is the same thing I've done in Sen a while back, except I made sure that it remains exactly the same as it was before.
=> Fix visual/potential crash when rewinding due to visualizer

osu.Game.Rulesets.Tau/Replays/TauAutoGenerator.cs
This fixes Autoplay issues with weird maps such as Centipede.
=> Fix Autoplay not properly considering multiple objects at the same time

osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs, osu.Game.Rulesets.Tau/Edit/TauSelectionHandler.cs, osu.Game.Rulesets.Tau/Judgements/TauJudgement.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauHitObject.cs, osu.Game.Rulesets.Tau/Scoring/TauScoreProcessor.cs, osu.Game.Rulesets.Tau/TauDifficultyCalculator.cs, osu.Game.Rulesets.Tau/TauRuleset.cs, osu.Game.Rulesets.Tau/UI/TauSettingsSubsection.cs, osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Also fixes the obsoleted code errors introduced by this update.
=> Bump ppy.osu.Game to 2020.1009.0

README.md
Thought I'd go ahead and add some basic but potentially helpful build instructions since the README was lacking them. Please feel free to add or change anything you'd like. These instructions should work for any platform that dotnet can be installed on.
=> Add basic build instructions to the README

osu.Game.Rulesets.Tau/Extensions.cs, osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs
This is an attempt to move away from the rather approximate AABB validation check and instead use angleDiffs.
The design is a WIP, and the code is far from clean and tidy. This is a quick attempt to make something functional and sufficient for testing and to form further discussion.
=> Complete rewrite of the cursor 

osu.Game.Rulesets.Tau.Tests/TestSceneGameplayCursor.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableHardBeat.cs, osu.Game.Rulesets.Tau/UI/Cursor/TauCursor.cs, osu.Game.Rulesets.Tau/UI/KiaiHitExplosion.cs, osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
i'll still have to remove the line going through the cursor to keep in line with the current design.
colouring will also be skinnable in the future.
=> Recolour gameplay elements

osu.Game.Rulesets.Tau/Objects/Drawables/DrawableTauJudgement.cs, osu.Game.Rulesets.Tau/Objects/Drawables/SkinnableLighting.cs, osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
This also fixes an issue with the colouring being incorrect.
=> Pool DrawableTauJudgements

osu.Game.Rulesets.Tau.Tests/Objects/TestSceneBeat.cs, osu.Game.Rulesets.Tau.Tests/TestSceneKiai.cs, osu.Game.Rulesets.Tau.Tests/osu.Game.Rulesets.Tau.Tests.csproj
=> Add more tests

osu.Game.Rulesets.Tau.Tests/TestSceneResumeOverlay.cs, osu.Game.Rulesets.Tau/UI/DrawableTauRuleset.cs, osu.Game.Rulesets.Tau/UI/TauResumeOverlay.cs
=> Implement ResumeOverlay

osu.Game.Rulesets.Tau.Tests/Objects/TestSceneSlider.cs, osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableBeat.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableSlider.cs, osu.Game.Rulesets.Tau/Objects/Drawables/DrawableSliderHead.cs, osu.Game.Rulesets.Tau/Objects/Slider.cs, osu.Game.Rulesets.Tau/Objects/SliderHeadBeat.cs, osu.Game.Rulesets.Tau/UI/TauPlayfield.cs
This also implements Slider heads which is required to make the HitSounds work properly.
=> Implement HitSounds for Sliders.

osu.Game.Rulesets.Tau/Edit/Blueprints/TauSelectionBlueprint.cs, osu.Game.Rulesets.Tau/Edit/TauBlueprintContainer.cs, osu.Game.Rulesets.Tau/Edit/TauSelectionHandler.cs, osu.Game.Rulesets.Tau/Mods/TauModLite.cs, osu.Game.Rulesets.Tau/Mods/TauModPerfect.cs, osu.Game.Rulesets.Tau/Replays/TauFramedReplayInputHandler.cs, osu.Game.Rulesets.Tau/TauRuleset.cs
I thought we had the Perfect mod in the ruleset... I wonder why we didn't..
Fully funcitonal.
=> Impliment Perfect mod and some code import sanity checks..

osu.Game.Rulesets.Tau/Skinning/Legacy/TauLegacySkinTransformer.cs
Fixes #218 
Simple fix for a long lasting bug.
=> Fix Legacy Skin components not rendering on playfield.

osu.Game.Rulesets.Tau/Difficulty/Skills/Aim.cs, osu.Game.Rulesets.Tau/Difficulty/Skills/Speed.cs, osu.Game.Rulesets.Tau/Difficulty/TauDifficultyAttributes.cs, osu.Game.Rulesets.Tau/Difficulty/TauDifficultyCalculator.cs, osu.Game.Rulesets.Tau/Difficulty/TauPerformanceAttribute.cs, osu.Game.Rulesets.Tau/Difficulty/TauPerformanceCalculator.cs, osu.Game.Rulesets.Tau/TauRuleset.cs
Current implementation only uses both aim and accuracy without misses in mind.
Also includes restructure to TauPerformanceContext
=> Implement Basic Performance Point Calculations

osu.Game.Rulesets.Tau.Tests/TestSceneKiaiEffects.cs, osu.Game.Rulesets.Tau/UI/Effects/KiaiEffect.cs, osu.Game.Rulesets.Tau/UI/Effects/KiaiEffectContainer.cs, osu.Game.Rulesets.Tau/UI/EffectsContainer.cs
=> Fallback to playfield's accent color if resulting hit colour is white

osu.Game.Rulesets.Tau/Localisation/ModStrings.cs, osu.Game.Rulesets.Tau/Localisation/Translations/Mods.resx, osu.Game.Rulesets.Tau/Localisation/Translations/UI.resx, osu.Game.Rulesets.Tau/Localisation/UiStrings.cs, osu.Game.Rulesets.Tau/Mods/TauModAutopilot.cs, osu.Game.Rulesets.Tau/Mods/TauModDifficultyAdjust.cs, osu.Game.Rulesets.Tau/Mods/TauModDual.cs, osu.Game.Rulesets.Tau/Mods/TauModEasy.cs, osu.Game.Rulesets.Tau/Mods/TauModFadeIn.cs, osu.Game.Rulesets.Tau/Mods/TauModFadeOut.cs, osu.Game.Rulesets.Tau/Mods/TauModFlashlight.cs, osu.Game.Rulesets.Tau/Mods/TauModHidden.cs, osu.Game.Rulesets.Tau/Mods/TauModImpossibleSliders.cs, osu.Game.Rulesets.Tau/Mods/TauModInverse.cs, osu.Game.Rulesets.Tau/Mods/TauModLenience.cs, osu.Game.Rulesets.Tau/Mods/TauModLite.cs, osu.Game.Rulesets.Tau/Mods/TauModNoScope.cs, osu.Game.Rulesets.Tau/Mods/TauModRelax.cs, osu.Game.Rulesets.Tau/Mods/TauModRoundabout.cs, osu.Game.Rulesets.Tau/Mods/TauModStrict.cs, osu.Game.Rulesets.Tau/Mods/TauModTraceable.cs, osu.Game.Rulesets.Tau/Statistics/PaddleDistributionGraph.cs, osu.Game.Rulesets.Tau/TauRuleset.cs, osu.Game.Rulesets.Tau/UI/TauResumeOverlay.cs, osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Following up on the merge of https://github.com/ppy/osu/pull/19695, I've decided to prepare early and go ahead and make the changes necessary.
~~Will also have to apply the same changes to #317 once that's merged.~~
New crowdin strings will be pushed later in the day (or tomorrow).
=> Add new mod and ui strings

osu.Game.Rulesets.Tau/Objects/Drawables/Pieces/StrictHardBeatPiece.cs, osu.Game.Rulesets.Tau/Objects/Slider.cs, osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
=> Fix strict hard beats not applying correct size

osu.Game.Rulesets.Tau/Difficulty/Skills/Aim.cs, osu.Game.Rulesets.Tau/Difficulty/Skills/Complexity.cs, osu.Game.Rulesets.Tau/Difficulty/Skills/Speed.cs, osu.Game.Rulesets.Tau/Difficulty/TauDifficultyCalculator.cs
| Title | SR (A) | SR (B) | DIFF | AP (A) | AP (B) | RX (A) | RX (B) |
|-------|:------:|:------:|:----:|:------:|:------:|:------:|:------:|
| [ArchWk - Supernovae (Irisu) [Intergalactic Wanderer]](https://osu.ppy.sh/b/3662171) | 15.90 | 16.76 | +0.86 | 15.90 | 16.33 | 8.74 | 7.93 |
| [Kobaryo & Matatabi Sound System - Precious Song Dedicated to the Stars (sansevieria1) [I Dedicated Myself to the Stars]](https://osu.ppy.sh/b/2854689) | 7.90 | 8.12 | +0.22 | 7.90 | 7.75 | 5.12 | 4.60 |
| [Ashrount - AureoLe \~for Triumph\~ (R3m) [FINAL]](https://osu.ppy.sh/b/3499015) | 9.26 | 9.40 | +0.14 | 9.26 | 8.60 | 6.92 | 6.27 |
| [PsyLine & Lunawatt & Brainstalker - Hightechnological (Ciyus Miapah) [Ultimate Devastation]](https://osu.ppy.sh/b/2183215) | 8.58 | 8.70 | +0.12 | 8.58 | 8.07 | 6.15 | …
=> Difficulty balance pass

osu.Game.Rulesets.Tau/Localisation/Translations/Beatmap.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Beatmap.zh-Hans.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Inputs.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Inputs.zh-Hans.resx, osu.Game.Rulesets.Tau/Localisation/Translations/KiaiType.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/KiaiType.zh-Hans.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Mods.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Mods.ru.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Mods.zh-Hans.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Settings.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/Settings.zh-Hans.resx, osu.Game.Rulesets.Tau/Localisation/Translations/UI.it.resx, osu.Game.Rulesets.Tau/Localisation/Translations/UI.zh-Hans.resx
Includes new languages: Italian, and Chinese simplified (partially)
Updated translation strings from: Russian
=> Pull latest translations

osu.Game.Rulesets.Tau/Allocation/MemoryPool.cs
fixes #520 
credit to @LumpBloom7 for knowing more dotnet than me
=> fix Span.Enumerator not existing in lazer mobile dotnet runtime

osu.Game.Rulesets.Tau/Beatmaps/TauBeatmapConverter.cs, osu.Game.Rulesets.Tau/Mods/TauModDifficultyAdjust.cs, osu.Game.Rulesets.Tau/Mods/TauModRoundabout.cs, osu.Game.Rulesets.Tau/osu.Game.Rulesets.Tau.csproj
Fixes #522 the right way unlike #523
=> Fix #522 by bumping `ppy.osu.Game` to `2025.403.0`
